camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    email:
  filter:
    create: All tasks
  job-execution:
    max-wait: 5000
spring:
  datasource:
    url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  h2.console.enabled: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username:
    password:
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
server.port: 8080